### ISSUE TITLE
Detayı olmayan kişiler de eklenebilir

### ISSUE THREAD

**Issue by ahmetcanaydemir** [AliYil/agac#1]
Soy ağacında detaylı bilgileri* yer almayıp da **Baba Adı** ve **Ana Adı**  sütunlarında sadece ismi bulunan kişiler de soy ağacında görselleştirilebilir.

> _*doğum ölüm tarihleri, medeni hali, durumu, il ilçe vb_

**Comment by AliYil** [comment]
216c6bf commit'inde ile düzeltildi. Öneri için teşekkürler.
