### ISSUE TITLE
Chromebook versiyon 63.0.3239.140 da calismadi

### ISSUE THREAD

**Issue by avnibu** [AliYil/agac#2]
Buraya reddit'ten geldim. Oncelikle elinize saglik. Guzel dusunulmus bir girisim. Fakat kendi agacim icin uygulamayi calistiramadim.

Tam olarak dogru kismi kopyaladigimdan emin degilim. `<table class="resultTable striped"></table> `arasindaki herseyi html icinden kopyalayip yeni bir html dosyasi olarak kaydettim. Ardindan kopyalayip yapistirinca konsolda asagidaki hata mesajini aldim:

`Uncaught TypeError: Cannot read property 'innerText' of undefined
    at (index):53`

Hata mesajinda su satira referans gosteriliyor:
`53                        gender: row.cells[1].innerText,`

Direkt neden e-devlet sayfasindan kopyalamadin be adam diyecek olabilirsiniz. Haklisiniz. Fakat onu da bir turlu beceremedim.

**Comment by avnibu** [comment]
Cocuklarin ve aciklamalarin oldugu `<tr>` taglerini silince calisti.

**Comment by AliYil** [comment]
#3 ile aynı sorun olduğundan kapatıyorum. 747641a ile düzelmiş olması gerek.
