### ISSUE TITLE
Alt soy bilgisi mevcut olunca çalışmıyor

### ISSUE THREAD

**Issue by AliYil** [AliYil/agac#3]

**Comment by AliYil** [comment]
747641a ile giderilmiş olması lazım. Alt soy bilgisi olan biri test edip doğrularsa kapatıyorum

**Comment by avnibu** [comment]
Calisiyor ama alt soy bireyleri agacta gorunmuyor.

**Comment by AliYil** [comment]
O zaman #4 açtım bunu kapatıyorum.

**Comment by rabiakarasan68** [comment]
evet altsoy bilgileri ağaçta görünmüyor ayrıca listede 1.sıradaki kişinin anne baba adı listede olduğu halde 1.sıradaki kişinin anne baba bilgiside ağaçta görünmüyor oda görünse iyi olur
